dist: bionic
language: python

python:
  - "3.7"

env:
  - GO111MODULE=on VERSION=1.12.10 OS=linux ARCH=amd64 GOPATH=${HOME}/go /usr/local/go/bin:${PATH}:${GOPATH}/bin

before_install:
  - wget -O /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz https://dl.google.com/go/go${VERSION}.${OS}-${ARCH}.tar.gz
  - sudo tar -C /usr/local -xzf /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libseccomp-dev pkg-config squashfs-tools cryptsetup
  - mkdir -p ${GOPATH}/src/github.com/sylabs
  - cd ${GOPATH}/src/github.com/sylabs
  - git clone https://github.com/sylabs/singularity.git
  - cd singularity
  - git checkout v3.4.1
  - ./mconfig
  - cd ./builddir
  - make
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - sudo python3 ./dev_utils.py build  # The sudo call doesn't use Python 3.7, but it's still used inside the container.
